# app-deployment.yaml (exemple pour dev)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: gestion-produits:latest
          imagePullPolicy: Never
          env:
            - name: DB_TYPE
              value: pgsql
            - name: DB_HOST
              value: postgres
            - name: DB_NAME
              value: gestion_produits
            - name: DB_USERNAME
              value: root
            - name: DB_PASSWORD
              value: root
            - name: APP_ENV
              value: development
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: dev
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 80
