version: '3'

services:
  # Service PHP/Apache
  app:
    build: .
    ports:
      - "5000:80"
    volumes:
      - ./php/www:/var/www/html
    depends_on:
      - db
    restart: always

  # Service MySQL
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/gestion_produits.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_produits
      MYSQL_USER: root
      MYSQL_PASSWORD: root

volumes:
  mysql_data: