version: '3'

services:
  # Service PHP/Apache - Production (MySQL)
  app-prod:
    build: .
    ports:
      - "5000:80"
    volumes:
      - ./php/www:/var/www/html
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: gestion_produits
      DB_TYPE: mysql
    restart: always

  # Service PHP/Apache - Development (PostgreSQL)
  app-dev:
    build: .
    ports:
      - "5001:80"
    volumes:
      - ./php/www:/var/www/html
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: gestion_produits
      DB_TYPE: pgsql
    restart: always

  # Service MySQL (Production)
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/gestion_produits.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gestion_produits
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  # Service PostgreSQL (Development)
  postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/gestion_produits_pg.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gestion_produits

volumes:
  mysql_data:
  postgres_data: