version: '3'

services:
  # Service PHP/Apache (Front-end)
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./php/www:/var/www/html
    depends_on:
      - db-mysql
      - db-postgres
    environment:
      - DB_MYSQL_HOST=db-mysql
      - DB_MYSQL_USER=root
      - DB_MYSQL_PASSWORD=root
      - DB_MYSQL_NAME=gestion_produits
      - DB_POSTGRES_HOST=db-postgres
      - DB_POSTGRES_USER=gestion_produits
      - DB_POSTGRES_PASSWORD=gestion_produits
      - DB_POSTGRES_NAME=gestion_produits
    restart: always

  # Service MySQL
  db-mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/gestion_produits.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=gestion_produits
      - MYSQL_USER=gestion_produits
      - MYSQL_PASSWORD=gestion_produits

  # Service PostgreSQL
  db-postgres:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/postgres/gestion_produits.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=gestion_produits
      - POSTGRES_PASSWORD=gestion_produits
      - POSTGRES_DB=gestion_produits

volumes:
  mysql_data:
  postgres_data: