apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-produits
  namespace: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gestion-produits
  template:
    metadata:
      labels:
        app: gestion-produits
    spec:
      containers:
      - name: gestion-produits
        image: gestion-produits:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: DB_MYSQL_HOST
          value: mysql
        - name: DB_MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: user
        - name: DB_MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: DB_MYSQL_NAME
          value: gestion_produits
        - name: DB_POSTGRES_HOST
          value: db-postgres
        - name: DB_POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: user
        - name: DB_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: DB_POSTGRES_NAME
          value: gestion_produits
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-produits
  namespace: prod
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: gestion-produits