apiVersion: apps/v1
kind: Deployment
metadata:
  name: gestion-produits  # Changé de gestion-produits-postgres
  namespace: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gestion-produits  # Changé de gestion-produits-postgres
  template:
    metadata:
      labels:
        app: gestion-produits  # Changé de gestion-produits-postgres
    spec:
      containers:
      - name: gestion-produits  # Changé de gestion-produits-postgres
        image: gestion-produits:postgres
        imagePullPolicy: Never
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gestion-produits  # Changé de gestion-produits-postgres
  namespace: dev
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  selector:
    app: gestion-produits  # Changé de gestion-produits-postgres