apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: prod
type: Opaque
data:
  root-password: cm9vdA== # root
  user: Z2VzdGlvbl9wcm9kdWl0cw== # gestion_produits
  password: Z2VzdGlvbl9wcm9kdWl0cw== # gestion_produits