apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
data:
  user: Z2VzdGlvbl9wcm9kdWl0cw== # gestion_produits
  password: Z2VzdGlvbl9wcm9kdWl0cw== # gestion_produits